export const REG_START = 'REG_START';
export const REG_SUCCESS = 'REG_SUCCESS';
export const REG_SUCCESS_WITH_WARNING = 'REG_SUCCESS_WITH_WARNING';
export const REG_FAILURE = 'REG_FAILURE';

export const ENABLE_REGISTER = 'ENABLE_REGISTER';
export const DISABLE_REGISTER = 'DISABLE_REGISTER';

export const ENABLE_LOGIN = 'ENABLE_LOGIN';
export const DISABLE_LOGIN = 'DISABLE_LOGIN';

export const REG_LOGOUT = 'REG_LOGOUT';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_SUCCESS_WITH_WARNING = 'LOGIN_SUCCESS_WITH_WARNING';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const POPULATE_LOGGEDIN_USER_DETAILS = 'POPULATE_LOGGEDiN_USER_DETAILS';

export const UPDATE_START = 'UPDATE_START';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_SUCCESS_WITH_WARNING = 'UPDATE_SUCCESS_WITH_WARNING';
export const UPDATE_FAILURE = 'UPDATE_FAILURE';
export const UPDATE_DETAILS = 'UPDATE_DETAILS';

export const LOGOUT = 'LOGOUT';